// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipesRepacoSayco.Data.Data;

#nullable disable

namespace RecipesRepacoSayco.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607140712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipesRepacoSayco.Data.Models.BatchProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("ActualValue1")
                        .HasColumnType("real");

                    b.Property<float?>("ActualValue2")
                        .HasColumnType("real");

                    b.Property<float?>("ActualValue3")
                        .HasColumnType("real");

                    b.Property<float?>("ActualValue4")
                        .HasColumnType("real");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Setpoint1")
                        .HasColumnType("real");

                    b.Property<float?>("Setpoint2")
                        .HasColumnType("real");

                    b.Property<float?>("Setpoint3")
                        .HasColumnType("real");

                    b.Property<float?>("Setpoint4")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BatchProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
